Repository CactuseSecurity/firewall-orchestrator, pull requests merged in 2022-02, with the labels that each got.

#1512 Filterline rework + Restsharp lib update
  roles/FWO.sln
  roles/importer/importer.pyproj
  roles/lib/files/FWO.Api.Client/APIConnection.cs
  roles/lib/files/FWO.Api.Client/Data/Device.cs
  roles/lib/files/FWO.Config.Api/ConfigDbAccess.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj
  roles/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs
  roles/lib/files/FWO.Logging/Log.cs
  roles/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj
  roles/lib/files/FWO.Middleware.Client/JwtReader.cs
  roles/lib/files/FWO.Middleware.Client/MiddlewareClient.cs
  roles/lib/files/FWO.Middleware/JwtConstants.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilter.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterBool.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterDateTimeRange.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterInt.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterNetwork.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterReportType.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterString.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeUnary.cs
  roles/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj
  roles/lib/files/FWO.Report.Filter/FilterTypes/DateTimeRange.cs
  roles/lib/files/FWO.Report.Filter/FilterTypes/ReportType.cs
  roles/lib/files/FWO.Report.Filter/Parser.cs
  roles/lib/files/FWO.Report.Filter/Scanner.cs
  roles/lib/files/FWO.Report.Filter/Token.cs
  roles/lib/files/FWO.Report.Filter/TokenKind.cs
  roles/lib/files/FWO.Report.Filter/TokenSyntax.cs
  roles/lib/files/FWO.Report/ReportRules.cs
  roles/middleware/files/FWO.Middleware.Server/Controllers/AuthenticationTokenController.cs
  roles/middleware/files/FWO.Middleware.Server/JwtWriter.cs
  roles/test/files/FWO.Test/FWO.Test.csproj
  roles/test/files/FWO.Test/FilterTest.cs
  roles/ui/files/FWO.UI/Pages/Login.razor
  roles/ui/files/FWO.UI/Pages/Reporting/Report.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsGroups.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsLdap.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsRoles.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsTenants.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsUsers.razor
  roles/ui/files/FWO.UI/Services/PasswordChanger.cs
  roles/ui/files/FWO.UI/Startup.cs
Labels: enhancement, optimization

#1581 hotfix missing import_id fk relation
  roles/database/files/upgrade/5.6.6.sql
Labels: hotfix

#1578 Display time + Async constructor
  roles/lib/files/FWO.Config.Api/ConfigDbAccess.cs
  roles/lib/files/FWO.Config.Api/GlobalConfig.cs
  roles/middleware/files/FWO.Middleware.Server/AutoDiscoverScheduler.cs
  roles/middleware/files/FWO.Middleware.Server/Program.cs
  roles/middleware/files/FWO.Middleware.Server/ReportScheduler.cs
  roles/ui/files/FWO.UI/Pages/Reporting/Schedule.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsDefaults.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsPasswordPolicy.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsRecertification.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsReport.razor
  roles/ui/files/FWO.UI/Startup.cs
Labels: bug, optimization
