Repository CactuseSecurity/firewall-orchestrator, pull requests merged in 2022-10, with the labels that each got.

#1863 Jwt Impersonation + Config messages + selected gateways + Custom dropdowns
  roles/database/files/sql/creation/fworch-create-constraints.sql
  roles/lib/files/FWO.Api.Client/Data/DeviceFilter.cs
  roles/lib/files/FWO.Api.Client/Data/UiUser.cs
  roles/lib/files/FWO.Api.Client/FWO.Api.Client.csproj
  roles/lib/files/FWO.Config.Api/Config.cs
  roles/lib/files/FWO.Config.Api/GlobalConfig.cs
  roles/lib/files/FWO.Config.Api/UserConfig.cs
  roles/lib/files/FWO.Middleware/RequestParameters/AuthenticationTokenParameters.cs
  roles/lib/files/FWO.Report.Filter/Scanner.cs
  roles/middleware/files/FWO.Middleware.Server/Controllers/AuthenticationServerController.cs
  roles/middleware/files/FWO.Middleware.Server/Controllers/AuthenticationTokenController.cs
  roles/middleware/files/FWO.Middleware.Server/Controllers/UserController.cs
  roles/middleware/files/FWO.Middleware.Server/FWO.Middleware.Server.csproj
  roles/middleware/files/FWO.Middleware.Server/JwtWriter.cs
  roles/middleware/files/FWO.Middleware.Server/Ldap.cs
  roles/middleware/files/FWO.Middleware.Server/Program.cs
  roles/middleware/files/FWO.Middleware.Server/ReportScheduler.cs
  roles/middleware/files/FWO.Middleware.Server/UiUserHandler.cs
  roles/ui/files/FWO.UI/Pages/Reporting/Report.razor
  roles/ui/files/FWO.UI/Pages/Reporting/ReportExport.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsLanguage.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsTenants.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsUsers.razor
  roles/ui/files/FWO.UI/Services/DomEventService.cs
  roles/ui/files/FWO.UI/Shared/DeviceSelection.razor
  roles/ui/files/FWO.UI/Shared/Dropdown.razor
  roles/ui/files/FWO.UI/Startup.cs
  roles/ui/files/FWO.UI/_Imports.razor
  roles/ui/files/FWO.UI/wwwroot/js/window.js
Labels: bug, enhancement, optimization

#1887 log locking
  roles/common/files/acquire_lock.py
  roles/common/files/release_lock.py
  roles/lib/files/FWO.Logging/Log.cs
  roles/middleware/files/FWO.Middleware.Server/JwtWriter.cs
  roles/middleware/files/FWO.Middleware.Server/ReportScheduler.cs
  roles/ui/files/FWO.UI/Pages/Request/PromoteObject.razor
  roles/ui/files/FWO.UI/wwwroot/css/site.css
Labels: bug

#1893 fix missing fworch user
  roles/common/tasks/main.yml
Labels: hotfix

#1892 Workflow module fixes
  roles/ui/files/FWO.UI/Pages/Request/DisplayAccessElements.razor
  roles/ui/files/FWO.UI/Pages/Request/DisplayRequestTask.razor
  roles/ui/files/FWO.UI/Pages/Request/RequestApprovals.razor
  roles/ui/files/FWO.UI/Services/RequestHandler.cs
Labels: bug

#1894 Fix button type
  roles/ui/files/FWO.UI/Pages/Request/DisplayAccessElements.razor
  roles/ui/files/FWO.UI/Pages/Request/DisplayRequestTask.razor
Labels: bug
