Repository CactuseSecurity/firewall-orchestrator, pull requests merged in 2022-05, with the labels that each got.

#1707 JWT expiry to config, move logout
  roles/database/files/sql/creation/fworch-fill-stm.sql
  roles/database/files/sql/idempotent/fworch-texts.sql
  roles/database/files/upgrade/5.7.1.sql
  roles/lib/files/FWO.Api.Client/APIcalls/auth/getUserByDbId.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/config/getConfigItemByKey.graphql
  roles/lib/files/FWO.Api.Client/Queries/ConfigQueries.cs
  roles/lib/files/FWO.Config.Api/Data/ConfigData.cs
  roles/middleware/files/FWO.Middleware.Server/JwtWriter.cs
  roles/middleware/files/FWO.Middleware.Server/Program.cs
  roles/middleware/files/FWO.Middleware.Server/UiUserHandler.cs
  roles/ui/files/FWO.UI/Pages/Settings/SettingsDefaults.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsReport.razor
  roles/ui/files/FWO.UI/Pages/Settings/SettingsUser.razor
  roles/ui/files/FWO.UI/Shared/MainLayout.razor
  roles/ui/files/FWO.UI/Shared/NavigationMenu.razor
Labels: not reproducible

#1715 Request module db changes + bugfix paper size + tests for config
  documentation/installer/install-for-testing.md
  roles/api/files/replace_metadata.json
  roles/database/files/sql/creation/fworch-create-constraints.sql
  roles/database/files/sql/creation/fworch-create-foreign-keys.sql
  roles/database/files/sql/creation/fworch-create-indices.sql
  roles/database/files/sql/creation/fworch-create-tables.sql
  roles/database/files/upgrade/5.7.1.sql
  roles/lib/files/FWO.Config.File/ConfigFile.cs
  roles/lib/files/FWO.Config.File/KeyImporter.cs
  roles/lib/files/FWO.Report/ReportBase.cs
  roles/test/files/FWO.Test/ApiConfigTest.cs
  roles/test/files/FWO.Test/ApiTest.cs
  roles/test/files/FWO.Test/ConfigFileTest.cs
  roles/test/files/FWO.Test/FilterTest.cs
  roles/test/files/FWO.Test/HtmlToPdfTest.cs
  roles/test/files/FWO.Test/SimulatedApiConnection.cs
  roles/test/files/FWO.Test/TestHelper.cs
  roles/test/files/FWO.Test/TestInitializer.cs
  roles/ui/files/FWO.UI/Pages/Reporting/ReportExport.razor
  roles/ui/files/FWO.UI/Services/PermissionEventService.cs
  roles/ui/files/FWO.UI/Shared/MainLayout.razor
Labels: bug, enhancement

#1718 Develop hotfix permissionService startup
  SECURITY.md
  inventory/group_vars/apiserver.yml
  roles/importer/files/importer/checkpointR8x/cpcommon.py
  roles/ui/files/FWO.UI/Startup.cs
Labels: hotfix
