Repository CactuseSecurity/firewall-orchestrator, pull requests merged in 2022-01, with the labels that each got.

#1393 Autodiscovery 5.5.6 first simple version
  .vscode/launch.json
  documentation/developer-docs/importer/FWO-import-api.md
  documentation/developer-docs/visual-studio/vscode-debugging.md
  documentation/revision-history.md
  inventory/group_vars/all.yml
  roles/api/files/replace_metadata.json
  roles/database/files/sql/creation/fworch-create-foreign-keys.sql
  roles/database/files/sql/creation/fworch-create-tables.sql
  roles/database/files/sql/creation/fworch-fill-stm.sql
  roles/database/files/sql/idempotent/fworch-texts.sql
  roles/database/files/upgrade/5.5.6.sql
  roles/importer/files/importer/checkpointR8x/parse_rule.py
  roles/importer/files/importer/fortiadom5ff/__init__.py
  roles/importer/files/importer/fortiadom5ff/autodiscover.sh
  roles/importer/files/importer/fortiadom5ff/discovery_logging.conf
  roles/importer/files/importer/fortiadom5ff/fmgr_network.py
  roles/importer/files/importer/fortiadom5ff/fmgr_rule.py
  roles/importer/files/importer/fortiadom5ff/fmgr_service.py
  roles/importer/files/importer/fortiadom5ff/fmgr_user.py
  roles/importer/files/importer/fortiadom5ff/fmgr_zone.py
  roles/importer/files/importer/fortiadom5ff/fwcommon.py
  roles/importer/files/importer/fortiadom5ff/getter.py
  roles/importer/files/importer/fortimanager5ff/fwcommon.py
  roles/lib/files/FWO.Api.Client/APIConnection.cs
  roles/lib/files/FWO.Api.Client/APIcalls/device/fragments/managementDetails.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/device/getDevicesByManagement.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/device/getSuperManagementsList.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/device/newManagement.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/device/updateManagement.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/report/getRelevantImportIdsAtTime.graphql
  roles/lib/files/FWO.Api.Client/Data/Management.cs
  roles/lib/files/FWO.Api.Client/Data/SuperManager.cs
  roles/lib/files/FWO.Api.Client/Queries/DeviceQueries.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryBase.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryCpMds.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs
  roles/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj
  roles/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs
  roles/lib/files/FWO.Report.Filter/DynGraphqlQuery.cs
  roles/lib/files/FWO.Report/ReportBase.cs
  roles/lib/tasks/main.yml
  roles/sample-data/tasks/main.yml
  roles/test/files/FWO_Test/ApiTest.cs-disabled
  roles/ui/files/FWO.UI/FWO.Ui.csproj
  roles/ui/files/FWO.UI/Pages/Settings/SettingsManagements.razor
  roles/webhook/tasks/main.yml
  site.yml
Labels: enhancement

#1405 Bugfixes
  roles/FWO.sln
  roles/lib/files/FWO.Api.Client/APIConnection.cs
  roles/lib/files/FWO.Api.Client/ApiSubscription.cs
  roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilter.cs
Labels: bug

#1413 Develop Fixing ApiTest
  .vscode/launch.json
  documentation/installer/install-for-testing.md
  inventory/group_vars/all.yml
  roles/FWO.sln
  roles/cleanup/tasks/main.yml
  roles/database/files/sql/idempotent/fworch-rule-import.sql
  roles/importer/files/importer/checkpointR8x/parse_rule.py
  roles/importer/files/importer/fortiadom5ff/fmgr_rule.py
  roles/lib/files/FWO.Config.File/ConfigFile.cs
  roles/middleware/tasks/middleware_install_dot_net.yml
  roles/test/files/FWO.Test/ApiTest.cs
  roles/test/files/FWO.Test/FWO.Test.csproj
  roles/test/files/FWO.Test/FilterTest.cs
  roles/test/files/FWO.Test/HtmlToPdfTest.cs
  roles/test/handlers/main.yml
  roles/test/tasks/main.yml
  roles/test/tasks/test-csharp.yml
  roles/test/tasks/write-config-test-user-creds.yml
  roles/ui/tasks/ui_install_dot_net.yml
  site.yml
Labels: bug

#1427 Develop minor (UI) fixes
  roles/database/files/sql/idempotent/fworch-texts.sql
  roles/importer/files/importer/fortiadom5ff/fmgr_rule.py
  roles/importer/files/importer/fortiadom5ff/fwcommon.py
  roles/importer/files/importer/fortiadom5ff/getter.py
  roles/openldap-server/tasks/main.yml
  roles/ui/files/FWO.UI/Pages/_Host.cshtml
  roles/ui/templates/httpd.conf
Labels: enhancement

#1432 fix wrong report time format
  roles/lib/files/FWO.Report.Filter/DynGraphqlQuery.cs
Labels: hotfix

#1435 improve sanitizer
  roles/lib/files/FWO.Api.Client/Data/Sanitizer.cs
  roles/lib/files/FWO.Api.Client/Data/Tenant.cs
  roles/lib/files/FWO.Api.Client/Data/UiLdapConnection.cs
  roles/lib/files/FWO.Api.Client/Data/UiUser.cs
  roles/lib/files/FWO.Api.Client/Data/UserGroup.cs
Labels: hotfix

#1455 Develop hotfix fortigate_demo legacy
  roles/cleanup/tasks/upgrade/5.6.2.yml
  roles/database/files/upgrade/5.6.2.sql
  roles/sample-data/tasks/create-devices.yml
Labels: hotfix

#1456 Develop hotfix wront db field name
  roles/database/files/upgrade/5.6.2.sql
Labels: hotfix

#1468 Fix Sanitizer
  roles/lib/files/FWO.Api.Client/Data/Sanitizer.cs
Labels: hotfix

#1484 Develop bugfixing forti-importer - prepare v5.6.4 main release
  .vscode/launch.json
  documentation/revision-history.md
  inventory/group_vars/all.yml
  roles/importer/files/importer/common.py
  roles/importer/files/importer/fortiadom5ff/fmgr_network.py
  roles/importer/files/importer/fortiadom5ff/fmgr_rule.py
  roles/importer/files/importer/fortiadom5ff/fwcommon.py
  roles/importer/files/importer/import-main-loop.py
  roles/importer/files/importer/import-mgm.py
Labels: bug

#1503 hotfix autodiscovery
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs
  roles/ui/files/FWO.UI/Pages/Settings/SettingsManagements.razor
Labels: hotfix

#1510 fix autodiscovery
  roles/database/files/sql/idempotent/fworch-texts.sql
  roles/lib/files/FWO.DeviceAutoDiscovery/AutoDiscoveryFortiManager.cs
  roles/ui/files/FWO.UI/Pages/Settings/SettingsManagements.razor
Labels: hotfix
