Repository CactuseSecurity/firewall-orchestrator, pull requests merged in 2023-07, with the labels that each got.

#2190 hotfix avoid default email port 25
  documentation/revision-history.md
  inventory/group_vars/all.yml
  roles/lib/files/FWO.Config.Api/Data/ConfigData.cs
Labels: hotfix

#2196 Compliance - Network Zones
  inventory/group_vars/all.yml
  roles/api/files/replace_metadata.json
  roles/database/files/sql/creation/fworch-create-constraints.sql
  roles/database/files/sql/creation/fworch-create-foreign-keys.sql
  roles/database/files/sql/creation/fworch-create-indices.sql
  roles/database/files/sql/creation/fworch-create-tables.sql
  roles/database/files/sql/idempotent/fworch-texts.sql
  roles/database/files/upgrade/6.5.0.sql
  roles/lib/files/FWO.Api.Client/APIConnection.cs
  roles/lib/files/FWO.Api.Client/APIcalls/compliance/addNetworkZone.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/compliance/deleteNetworkZone.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/compliance/getNetworkZones.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/compliance/updateNetworkZone.graphql
  roles/lib/files/FWO.Api.Client/APIcalls/compliance/updateNetworkZoneCommunication.graphql
  roles/lib/files/FWO.Api.Client/ApiSubscription.cs
  roles/lib/files/FWO.Api.Client/Data/ComplianceNetworkZone.cs
  roles/lib/files/FWO.Api.Client/Data/DeviceType.cs
  roles/lib/files/FWO.Api.Client/Data/NetworkZone.cs
  roles/lib/files/FWO.Api.Client/GraphQlApiConnection.cs
  roles/lib/files/FWO.Api.Client/GraphQlApiSubscription.cs
  roles/lib/files/FWO.Api.Client/JsonCustomConverters.cs
  roles/lib/files/FWO.Api.Client/JsonStringConverter.cs
  roles/lib/files/FWO.Api.Client/Queries/ComplianceQueries.cs
  roles/lib/files/FWO.Middleware.Client/MiddlewareClient.cs
  roles/middleware/files/FWO.Middleware.Server/Program.cs
  roles/middleware/files/FWO.Middleware.Server/ReportScheduler.cs
  roles/test/files/FWO.Test/SimulatedApiConnection.cs
  roles/ui/files/FWO.UI/Auth/AuthStateProvider.cs
  roles/ui/files/FWO.UI/Pages/Compliance/IpAddressInput.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZoneTable.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesChecks.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesConfiguration.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesMatrix.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesMatrix.razor.css
  roles/ui/files/FWO.UI/Pages/Login.razor
  roles/ui/files/FWO.UI/Pages/Logout.razor
  roles/ui/files/FWO.UI/Pages/Reporting/Archive.razor
  roles/ui/files/FWO.UI/Pages/Reporting/Schedule.razor
  roles/ui/files/FWO.UI/Pages/_Host.cshtml
  roles/ui/files/FWO.UI/Program.cs
  roles/ui/files/FWO.UI/Services/NetworkZoneService.cs
  roles/ui/files/FWO.UI/Shared/ComplianceLayout.razor
  roles/ui/files/FWO.UI/Shared/Dropdown.razor
  roles/ui/files/FWO.UI/Shared/EditList.razor
  roles/ui/files/FWO.UI/Shared/EditList.razor.css
  roles/ui/files/FWO.UI/Shared/ExpandableList.razor
  roles/ui/files/FWO.UI/Shared/MainLayout.razor
  roles/ui/files/FWO.UI/Shared/MonitoringLayout.razor
  roles/ui/files/FWO.UI/Shared/NavigationMenu.razor
  roles/ui/files/FWO.UI/Shared/SettingsLayout.razor
  roles/ui/files/FWO.UI/Startup.cs
  roles/ui/files/FWO.UI/appsettings.json
Labels: enhancement

#2210 Compliance+ Audit Log Fixes
  documentation/revision-history-develop.md
  inventory/group_vars/all.yml
  roles/ui/files/FWO.UI/Pages/Compliance/ComplianceLayout.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZoneTable.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesChecks.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesConfiguration.razor
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesMatrix.razor
  roles/ui/files/FWO.UI/Pages/Login.razor
  roles/ui/files/FWO.UI/Pages/Logout.razor
  roles/ui/files/FWO.UI/Services/CircuitHandlerService.cs
  roles/ui/files/FWO.UI/Shared/MainLayout.razor
  roles/ui/files/FWO.UI/Shared/NavigationMenu.razor
  roles/ui/files/FWO.UI/Startup.cs
Labels: bug

#2211 compliance check type button
  roles/ui/files/FWO.UI/Pages/Compliance/ZonesChecks.razor
Labels: bug
